"""sdfsdfds

Revision ID: ae5f37216305
Revises: 
Create Date: 2021-05-26 08:32:29.978595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae5f37216305'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('cases', sa.Integer(), nullable=True),
    sa.Column('deaths', sa.Integer(), nullable=True),
    sa.Column('recoveries', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Records_country'), 'Records', ['country'], unique=False)
    op.create_index(op.f('ix_Records_id'), 'Records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Records_id'), table_name='Records')
    op.drop_index(op.f('ix_Records_country'), table_name='Records')
    op.drop_table('Records')
    # ### end Alembic commands ###
