"""sdfsd

Revision ID: b13cbda52516
Revises: ae5f37216305
Create Date: 2021-05-26 08:35:47.310676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b13cbda52516'
down_revision = 'ae5f37216305'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
